server:
  port: 8080

spring:
  application:
    name: mountana-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    url: jdbc:postgresql://:${DB_PORT:5432}/xxxxxx?currentSchema=app
    url: jdbc:postgresql://ep-blue-silence-02842456.ap-southeast-1.aws.neon.tech/mountana?user=pradnyadarsana13&password=aJpyrziT2C1F&sslmode=require
  #    username:
  #    password:
    hikari:
      pool-name: MountanaSpringJPAHikariCP
      schema: public #app
      connection-timeout: 30000
      idle-timeout: 50000
      leak-detection-threshold: 50000
      max-lifetime: 50000
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: false
    tomcat:
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.default_schema: public #app
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800

springdoc:
  api-docs:
    path: /api-docs
    # Specify the path of the Swagger UI
  swagger-ui:
    path: /swagger-ui.html
    # Enable or disable Swagger UI
    enabled: true

external-services:
  image-assets-url: https://d1vd1wbsgnc7gm.cloudfront.net/
