# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

#    - name: Build and Push Docker Image
#      uses: mr-smithers-excellent/docker-build-push@v4
#      with:
#        image: pradnyadarsana/mountana-mountain-service
#        registry: docker.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build & Push Action
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@f8f78238603ab7953b961d99dc93ef0701295c60
      uses: mr-smithers-excellent/docker-build-push@v6.2
      with:
        # Name of the Docker image
        image: pradnyadarsana/mountana-api
        # Tags override for Docker image
        tags: latest
        # Target Docker registry
        registry: docker.io
        # Docker registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Docker registry password
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildArgs: AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} , AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

#     - name: Kubernetes Deployment
#       # You may pin to the exact commit or the version.
#       # uses: TanmoySG/k-deploy-action@5f80b044093190fc872281a5f6372105f66260b6
#       uses: TanmoySG/k-deploy-action@v0.2.2-alpha
#       with:
#         # Path to Kubeconfig
#         kubeconfig: ./kubeconfig.yaml
#         # Kubernetes Namespace
# #        namespace: mountana
#         # Path to manifest Files
#         manifest: ./k8s-deploy.yml

    # - name: Deploy
    #   uses: bankfliptech/deploy-to-render@v1
    #   with:
    #     serviceId: ${{ secrets.RENDER_SERVICE_ID }}
    #     apiKey: ${{ secrets.RENDER_API_KEY }}
    #     deployHookURL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

    # - name: Render Deployment
    #   # You may pin to the exact commit or the version.
    #   # uses: sws2apps/render-deployment@71f9c369fdc647d975eb7f92d3f9bc603e1938d6
    #   uses: sws2apps/render-deployment@v1.6.0
    #   with:
    #     # The Service ID of your Render service
    #     serviceId: ${{ secrets.RENDER_SERVICE_ID }}
    #     # Your personal API key to interact with Render
    #     apiKey: ${{ secrets.RENDER_API_KEY }}
    #     # Specify if having multiple deployment is allowed, optional, default is true
    #     multipleDeployment: false 

